### ISSUE TITLE
panic: invalid character '1' after top-level value

### ISSUE THREAD

**Issue by JvGinkel** [mpdroog/slackd#1]
panic: invalid character '1' after top-level value

goroutine 1 [running]:
main.main()
    /home/golangcode/src/slackd/main.go:153 +0xcb6

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/lib/golang/src/runtime/asm_amd64.s:1696 +0x1
panic: invalid character 'E' looking for beginning of value

goroutine 1 [running]:
main.main()
    /home/golangcode/src/slackd/main.go:153 +0xcb6

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/lib/golang/src/runtime/asm_amd64.s:1696 +0x1
panic: invalid character '1' after top-level value

goroutine 1 [running]:
main.main()
    /home/golangcode/src/slackd/main.go:153 +0xcb6

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/lib/golang/src/runtime/asm_amd64.s:1696 +0x1

**Comment by mpdroog** [comment]
It sounds like incomplete JSON-data trying to be parsed.
I've done a bugfix in de beanstalk-lib 5days ago, this might be missing on your compile server:
https://github.com/mpdroog/beanstalkd/commit/4ea3abb7568032033292cdb27e8f5ea9116be1b9

Please recompile when you've fetched the latest beanstalkd-lib :)

```
cd $GOPATH/src/github.com/mpdroog/beanstalkd
git pull origin master
```

**Comment by mpdroog** [comment]
You're right there's another bug in the beanstalkd-lib
https://github.com/mpdroog/beanstalkd/commit/bf387addf0025bf39946acf242f5442f97d45802
